version: '3.8'

services:
  cuda-container:
    image: my-custom-image
    container_name: ubuntu_22.04-cuda_12.4.1-s1
    runtime: nvidia
    ipc: host
    working_dir: /home/arch
    volumes:
      - ./:/home/arch/Work
    stdin_open: true    # 对应 -i
    tty: true          # 对应 -t
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
