version: '3.8'

services:
  cuda-container:
    image: archlinux:latest
    container_name: archlinux
    runtime: nvidia
    ipc: host
    ports:
      - "2022:22"
    volumes:
      - ./:/workspace
    stdin_open: true
    tty: true
    # use your host user's UID and GID
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
